api/urls.py
from django.urls import path

from api.views.account import AccountView
from api.views.telegram import TelegramMailingView
from api.views.task_status import TaskStateView

app_name = 'api'

urlpatterns = [
    path('accounts', AccountView.as_view(), name='accounts'),
    path('telegram/mailing', TelegramMailingView.as_view(), name='telegram'),
    path('task/status', TaskStateView.as_view(), name='task_status'),
]

post/urls.py
from django.urls import path

from post.views.list import PostList
from post.views.create import CreateView
from post.views.edit import EditView
from post.views.delete import DeleteView

app_name = 'post'

urlpatterns = [
    path('list', PostList.as_view(), name='list'),
    path('create', CreateView.as_view(), name='create'),
    path('edit/<int:post_id>', EditView.as_view(), name='edit'),
    path('delete/<int:post_id>', DeleteView.as_view(), name='delete'),
]

terrapro_admin/urls.py
from django.conf import settings
from django.urls import path, include

from .views import HomeView


urlpatterns = [
    path('api/v1/', include([
        path('', include('api.urls', namespace='api')),
    ])),

    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('account.urls')),
    path('post/', include('post.urls')),
    path('city/', include('city.urls')),
    path('branch/', include('branch.urls')),
    path('report/', include('report.urls')),
]

post/models.py
class FileType:
    IMAGE = 'image'
    VIDEO = 'video'
    DOCUMENT = 'document'

    CHOICES = [
        (IMAGE, 'Изображение'),
        (VIDEO, 'Видео'),
        (DOCUMENT, 'Документ'),
    ]

post/views/create.py
from django.shortcuts import render, redirect, reverse
from django.views import View

from api.models import Post

from post.form import PostForm


class CreateView(View):
    def get(self, request):
        form = PostForm()

        return render(request, template_name='post.html', context={'form': form})

    def post(self, request):
        form = PostForm(request.POST, request.FILES)

        if not form.is_valid():
            return render(request, template_name='post.html', context={'form': form})

        post = Post(
            text_rus=form.cleaned_data.get('text_rus'),
            text_eng=form.cleaned_data.get('text_eng'),
            text_uzb=form.cleaned_data.get('text_uzb'),
            desposition=form.cleaned_data.get('desposition'),
            tg_image_id=form.cleaned_data.get('image'),
            tg_video_id=form.cleaned_data.get('video'),
            tg_document_id=form.cleaned_data.get('document'),
            is_published=form.cleaned_data.get('is_published'),
        )
        post.save()

        return redirect(reverse('post:list'))

post/views/delete.py
from django.shortcuts import redirect, reverse
from django.views import View

from api.models import Post


class DeleteView(View):
    def post(self, request, post_id):
        Post.objects.get(pk=post_id).delete()

        return redirect(reverse('post:list'))

post/views/edit.py
from django.shortcuts import render, redirect, reverse
from django.views import View

from api.models import Post

from post.form import PostForm


class EditView(View):
    def get(self, request, post_id):
        post = self._get_post(post_id)

        form = PostForm(post.to_dict())

        return render(request, template_name='post.html', context={'form': form})

    def post(self, request, post_id):
        post = self._get_post(post_id)
        form = PostForm(request.POST, request.FILES)

        if not form.is_valid():
            return render(request, template_name='post.html', context={'form': form})

        post.text_rus = form.cleaned_data.get('text_rus')
        post.text_eng = form.cleaned_data.get('text_eng')
        post.text_uzb = form.cleaned_data.get('text_uzb')
        post.desposition = form.cleaned_data.get('desposition')
        post.is_published = form.cleaned_data.get('is_published')

        image = form.cleaned_data.get('image')
        print(image)
        if image:
            post.tg_image_id = image

        video = form.cleaned_data.get('video')
        print(video)
        if video:
            post.tg_video_id = video

        document = form.cleaned_data.get('document')
        print(document)
        if document:
            post.tg_document_id = document

        post.save()

        return redirect(reverse('post:list'))

    def _get_post(self, post_id):
        return Post.objects.get(pk=post_id)

post/views/list.py
from django.shortcuts import render
from django.views import View

from api.models import Post


class PostList(View):
    def get(self, request):
        posts = Post.objects.all()

        return render(request, template_name='posts.html', context={'posts': posts})

post/views/post.py
from django.shortcuts import render, redirect, reverse
from django.views import View

from api.models import Post

from post.form import PostForm


class PostView(View):
    def get(self, request):
        form = PostForm()

        return render(request, template_name='post.html', context={'form': form})

    def post(self, request):
        form = PostForm(request.POST, request.FILES)

        if not form.is_valid():
            return render(request, template_name='post.html', context={'form': form})

        post = Post(
            text_rus=form.cleaned_data.get('text_rus'),
            text_eng=form.cleaned_data.get('text_eng'),
            text_uzb=form.cleaned_data.get('text_uzb'),
            desposition=form.cleaned_data.get('desposition'),
            tg_image_id=form.cleaned_data.get('image'),
            tg_video_id=form.cleaned_data.get('video'),
            tg_document_id=form.cleaned_data.get('document')
        )
        post.save()

        return redirect(reverse('post:list'))

post/templates/post.html
{% extends "base.html" %}
{% load html_attrs %}

{% block content %}
<form role="form" method="post" enctype="multipart/form-data" novalidate>
{% csrf_token %}
    <div class="post_form__contaner">
        <div class="card">
            <div class="card-header">
                Добавление поста
            </div>
            <div class="card-body">
                <div class="form-group">
                    {{ form.text_rus.label_tag }}
                    {% if form.text_rus.errors %}
                        {{ form.text_rus|html_attrs:'"class": "form-control is-invalid"' }}
                    {% else %}
                        {{ form.text_rus|html_attrs:'"class": "form-control"' }}
                    {% endif %}
                    <h5 class="text-red">{{ form.text_rus.errors }}</h5>
                </div>
                <div class="form-group">
                    {{ form.text_eng.label_tag }}
                    {% if form.text_eng.errors %}
                        {{ form.text_eng|html_attrs:'"class": "form-control is-invalid"' }}
                    {% else %}
                        {{ form.text_eng|html_attrs:'"class": "form-control"' }}
                    {% endif %}
                    <h5 class="text-red">{{ form.text_eng.errors }}</h5>
                </div>
                <div class="form-group">
                    {{ form.text_uzb.label_tag }}
                    {% if form.text_uzb.errors %}
                        {{ form.text_uzb|html_attrs:'"class": "form-control is-invalid"' }}
                    {% else %}
                        {{ form.text_uzb|html_attrs:'"class": "form-control"' }}
                    {% endif %}
                    <h5 class="text-red">{{ form.text_uzb.errors }}</h5>
                </div>
                <div class="form-group">
                    {{ form.desposition.label_tag }}
                    {% if form.desposition.errors %}
                        {{ form.desposition|html_attrs:'"class": "form-control is-invalid"' }}
                    {% else %}
                        {{ form.desposition|html_attrs:'"class": "form-control"' }}
                    {% endif %}
                    <h5 class="text-red">{{ form.desposition.errors }}</h5>
                </div>
                <div class="form-group">
                    {{ form.image.label_tag }}
                    {% if form.image.errors %}
                        {{ form.image|html_attrs:'"class": "form-control is-invalid"' }}
                    {% else %}
                        {{ form.image|html_attrs:'"class": "form-control"' }}
                    {% endif %}
                    <h5 class="text-red">{{ form.image.errors }}</h5>
                </div>
                <div class="form-group">
                    {{ form.video.label_tag }}
                    {% if form.video.errors %}
                        {{ form.video|html_attrs:'"class": "form-control is-invalid"' }}
                    {% else %}
                        {{ form.video|html_attrs:'"class": "form-control"' }}
                    {% endif %}
                    <h5 class="text-red">{{ form.video.errors }}</h5>
                </div>
                <div class="form-group">
                    {{ form.document.label_tag }}
                    {% if form.document.errors %}
                        {{ form.document|html_attrs:'"class": "form-control is-invalid"' }}
                    {% else %}
                        {{ form.document|html_attrs:'"class": "form-control"' }}
                    {% endif %}
                    <h5 class="text-red">{{ form.document.errors }}</h5>
                </div>
                <div class="form-group">
                    {{ form.is_published.label_tag }}
                    {{ form.is_published|html_attrs:'"class": "form-control"' }}
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-info">Сохранить</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

post/templates/posts.html
{% extends "base.html" %}

{% block content %}
    <div class="post_list__container">
        <div class="card">
            <div class="card-header">
                <div class="card-header-buttons-container">
                    <a href="{% url 'post:create' %}" class="btn btn-block btn-outline-success btn-create">
                        Добавить пост <i class="fa fa-plus"></i>
                    </a>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th style="width: 20px">ID</th>
                            <th>Текст</th>
                            <th>Опубликован</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for post in posts %}
                            <tr>
                                <td>{{ post.id }}</td>
                                <td>{{ post.text_rus }}</td>
                                <td>{% if post.is_published %}Да{% endif %}</td>
                                <td class="edit-td">
                                    <div class="td-content">
                                        <a href="{% url 'post:edit' post_id=post.id %}" class="btn btn-block btn-outline-primary edit-btn">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                    </div>
                                </td>
                                <td class="edit-td">
                                    <div class="td-content">
                                        <a href="{% url 'post:delete' post_id=post.id %}" class="btn btn-block btn-outline-danger delete-btn">
                                            <i class="fa fa-trash-alt"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}