api/urls.py
from django.urls import path

from api.views.account import AccountView
from api.views.telegram import TelegramMailingView
from api.views.task_status import TaskStateView

app_name = 'api'

urlpatterns = [
    path('accounts', AccountView.as_view(), name='accounts'),
    path('telegram/mailing', TelegramMailingView.as_view(), name='telegram'),
    path('task/status', TaskStateView.as_view(), name='task_status'),
]

city/urls.py
from django.urls import path

from city.views import ListView, CreateView, EditView, DeleteView

app_name = 'city'

urlpatterns = [
    path('list', ListView.as_view(), name='list'),
    path('create', CreateView.as_view(), name='create'),
    path('edit/<int:city_id>', EditView.as_view(), name='edit'),
    path('delete/<int:city_id>', DeleteView.as_view(), name='delete'),
]

terrapro_admin/urls.py
from django.conf import settings
from django.urls import path, include

from .views import HomeView


urlpatterns = [
    path('api/v1/', include([
        path('', include('api.urls', namespace='api')),
    ])),

    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('account.urls')),
    path('post/', include('post.urls')),
    path('city/', include('city.urls')),
    path('branch/', include('branch.urls')),
    path('report/', include('report.urls')),
]

city/views.py
from django.shortcuts import render, redirect, reverse
from django.views import View

from api.models import Cite, Branche

from city.form import CityForm


class ListView(View):
    def get(self, request):
        cities = Cite.objects.all()

        return render(request, 'cities.html', context={'cities': cities})


class CreateView(View):
    def get(self, request):
        form = CityForm()

        return render(request, 'city.html', context={'form': form})

    def post(self, request):
        form = CityForm(request.POST)

        if not form.is_valid():
            return render(request, 'city.html', context={'form': form})

        form.save()

        return redirect(reverse('city:list'))


class EditView(View):
    def get(self, request, city_id):
        city = self._get_city(city_id)

        form = CityForm(instance=city)

        return render(request, 'city.html', context={'form': form})

    def post(self, request, city_id):
        city = self._get_city(city_id)

        form = CityForm(request.POST, instance=city)

        if not form.is_valid():
            return render(request, 'city.html', context={'form': form})

        form.save()

        return redirect(reverse('city:list'))

    def _get_city(self, city_id):
        return Cite.objects.get(pk=city_id)


class DeleteView(View):
    def post(self, request, city_id):
        Branche.objects.filter(cites_id=city_id).delete()
        Cite.objects.get(pk=city_id).delete()

        return redirect(reverse('city:list'))

city/templates/cities.html
{% extends "base.html" %}

{% block content %}
    <div class="post_list__container">
        <div class="card">
            <div class="card-header">
                <div class="card-header-buttons-container">
                    <a href="{% url 'city:create' %}" class="btn btn-block btn-outline-success btn-create">
                        Добавить город <i class="fa fa-plus"></i>
                    </a>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th style="width: 20px">ID</th>
                            <th>Название</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for city in cities %}
                            <tr>
                                <td>{{ city.id }}</td>
                                <td>{{ city.ru_name }}</td>
                                <td class="edit-td">
                                    <div class="td-content">
                                        <a href="{% url 'city:edit' city_id=city.id %}" class="btn btn-block btn-outline-primary edit-btn">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                    </div>
                                </td>
                                <td class="edit-td">
                                    <div class="td-content">
                                        <a href="{% url 'city:delete' city_id=city.id %}" class="btn btn-block btn-outline-danger delete-btn">
                                            <i class="fa fa-trash-alt"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

city/templates/city.html
{% extends "base.html" %}
{% load html_attrs %}

{% block content %}
<form role="form" method="post" enctype="multipart/form-data" novalidate>
{% csrf_token %}
    <div class="post_form__contaner">
        <div class="card">
            <div class="card-header">
                Добавление города
            </div>
            <div class="card-body">
                <div class="form-group">
                    {{ form.ru_name.label_tag }}
                    {% if form.ru_name.errors %}
                        {{ form.ru_name|html_attrs:'"class": "form-control is-invalid"' }}
                    {% else %}
                        {{ form.ru_name|html_attrs:'"class": "form-control"' }}
                    {% endif %}
                    <h5 class="text-red">{{ form.ru_name.errors }}</h5>
                </div>
                <div class="form-group">
                    {{ form.uz_name.label_tag }}
                    {% if form.uz_name.errors %}
                        {{ form.uz_name|html_attrs:'"class": "form-control is-invalid"' }}
                    {% else %}
                        {{ form.uz_name|html_attrs:'"class": "form-control"' }}
                    {% endif %}
                    <h5 class="text-red">{{ form.uz_name.errors }}</h5>
                </div>
                <div class="form-group">
                    {{ form.en_name.label_tag }}
                    {% if form.en_name.errors %}
                        {{ form.en_name|html_attrs:'"class": "form-control is-invalid"' }}
                    {% else %}
                        {{ form.en_name|html_attrs:'"class": "form-control"' }}
                    {% endif %}
                    <h5 class="text-red">{{ form.en_name.errors }}</h5>
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-info">Сохранить</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}