api/urls.py
from django.urls import path

from api.views.account import AccountView
from api.views.telegram import TelegramMailingView
from api.views.task_status import TaskStateView

app_name = 'api'

urlpatterns = [
    path('accounts', AccountView.as_view(), name='accounts'),
    path('telegram/mailing', TelegramMailingView.as_view(), name='telegram'),
    path('task/status', TaskStateView.as_view(), name='task_status'),
]

branch/urls.py
from django.urls import path

from branch.views import ListView, CreateView, EditView, DeleteView

app_name = 'branch'

urlpatterns = [
    path('list', ListView.as_view(), name='list'),
    path('create', CreateView.as_view(), name='create'),
    path('edit/<int:branch_id>', EditView.as_view(), name='edit'),
    path('delete/<int:branch_id>', DeleteView.as_view(), name='delete'),
]

city/urls.py
from django.urls import path

from city.views import ListView, CreateView, EditView, DeleteView

app_name = 'city'

urlpatterns = [
    path('list', ListView.as_view(), name='list'),
    path('create', CreateView.as_view(), name='create'),
    path('edit/<int:city_id>', EditView.as_view(), name='edit'),
    path('delete/<int:city_id>', DeleteView.as_view(), name='delete'),
]

post/urls.py
from django.urls import path

from post.views.list import PostList
from post.views.create import CreateView
from post.views.edit import EditView
from post.views.delete import DeleteView

app_name = 'post'

urlpatterns = [
    path('list', PostList.as_view(), name='list'),
    path('create', CreateView.as_view(), name='create'),
    path('edit/<int:post_id>', EditView.as_view(), name='edit'),
    path('delete/<int:post_id>', DeleteView.as_view(), name='delete'),
]

report/urls.py
from django.urls import path

from report.views import AccountReportView, BlockedUserReportView


app_name = 'report'

urlpatterns = [
    path('accounts', AccountReportView.as_view(), name='accounts'),
    path('user_block', BlockedUserReportView.as_view(), name='user_block'),
]

terrapro_admin/urls.py
from django.conf import settings
from django.urls import path, include

from .views import HomeView


urlpatterns = [
    path('api/v1/', include([
        path('', include('api.urls', namespace='api')),
    ])),

    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('account.urls')),
    path('post/', include('post.urls')),
    path('city/', include('city.urls')),
    path('branch/', include('branch.urls')),
    path('report/', include('report.urls')),
]

templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TerraPro Admin</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="{% static "vendor/fontawesome/fontawesome-free/css/all.css" %}">
    <link rel="stylesheet" href="{% static "vendor/admin-lte/dist/css/adminlte.css" %}">
    <link rel="stylesheet" href="{% static "vendor/sweetalert2/dist/sweetalert2.css" %}">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static "vendor/daterangepicker/daterangepicker.css" %}">
    <link rel="stylesheet" href="{% static "css/styles.css" %}">

</head>
<body class="hold-transition layout-top-nav">
<div class="wrapper">

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
        <div class="container">
            <a href="{% url 'home' %}" class="navbar-brand">
                <span class="brand-text">TerraPro</span>
            </a>
            <div class="collapse navbar-collapse order-3" id="navbarCollapse">
                <!-- Left navbar links -->
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{% url 'post:list' %}" class="nav-link">Посты</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'city:list' %}" class="nav-link">Города</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'branch:list' %}" class="nav-link">Филиалы</a>
                    </li>
                </ul>
            </div>
            <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
                <!-- Notifications Dropdown Menu -->
                <li class="nav-item">
                    {{ user.firstname }}
                </li>
                <li class="nav-item">
                    <a href="{% url 'account:logout' %}">Выйти</a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- /.navbar -->

    <div class="content-wrapper">
        <div class="content-header">
            <div class="container">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h3 class="m-0">{% block content_header %}{% endblock %}</h3>
                    </div><!-- /.col -->
                </div>
            </div>
        </div>
        <div class="content">
            <div class="container">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

    <footer class="main-footer">
    </footer>
</div>

<script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
<script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<script src="{% static "vendor/fontawesome/fontawesome-free/js/all.js" %}"></script>
<script src="{% static "vendor/admin-lte/dist/js/adminlte.js" %}"></script>
<script src="{% static "vendor/custom-control/bs-custom-file-input.js" %}"></script>
<script src="{% static "vendor/daterangepicker/moment.min.js" %}"></script>
<script src="{% static "vendor/daterangepicker/daterangepicker.js" %}"></script>
<script src="{% static "vendor/sweetalert2/dist/sweetalert2.js" %}"></script>
<script src="{% static "vendor/sweetalert2/dist/sweetalert2.all.js" %}"></script>
<script src="{% static "js/main.js" %}"></script>

</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-info">
                <div class="inner">
                    <h3>{{ users_count }}</h3>
                    <div class="icon">
                        <i class="ion ion-person-add"></i>
                    </div>
                    <div class="box-title">
                        Пользователей
                    </div>
                </div>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-warning">
                <div class="inner">
                    <h3>{{ cities }}</h3>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <div class="box-title">
                        Городов
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-info">
                <div class="inner">
                    <h3>{{ branches }}</h3>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <div class="box-title">
                        Филиалов
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="card card-info card-report">
        <div class="card-header">
            <h3 class="card-title">Выгрузка отчета</h3>
        </div>
        <div class="card-body">
            <form role="form" action="{% url 'report:accounts' %}" method="post" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    <label>Период</label>

                    <div class="input-group">
                        <div class="input-group-prepend">
                      <span class="input-group-text">
                        <i class="far fa-calendar-alt"></i>
                      </span>
                        </div>
                        <input type="text" name="report_daterange" class="form-control float-right" id="report_daterange">
                    </div>
                    <!-- /.input group -->
                </div>
                <button type="submit" class="btn btn-info">Выгрузить</button>
            </form>
        </div>
        <!-- /.card-body -->
    </div>

    <div class="card card-info card-report">
        <div class="card-header">
            <h3 class="card-title">Отчет по блокировакам бота</h3>
        </div>
        <div class="card-body">
            <form role="form" action="{% url 'report:user_block' %}" method="post" novalidate>
                {% csrf_token %}
                <button type="submit" class="btn btn-info">Выгрузить</button>
            </form>
        </div>
        <!-- /.card-body -->
    </div>
{% endblock %}