api/urls.py
from django.urls import path

from api.views.account import AccountView
from api.views.telegram import TelegramMailingView
from api.views.task_status import TaskStateView

app_name = 'api'

urlpatterns = [
    path('accounts', AccountView.as_view(), name='accounts'),
    path('telegram/mailing', TelegramMailingView.as_view(), name='telegram'),
    path('task/status', TaskStateView.as_view(), name='task_status'),
]

branch/urls.py
from django.urls import path

from branch.views import ListView, CreateView, EditView, DeleteView

app_name = 'branch'

urlpatterns = [
    path('list', ListView.as_view(), name='list'),
    path('create', CreateView.as_view(), name='create'),
    path('edit/<int:branch_id>', EditView.as_view(), name='edit'),
    path('delete/<int:branch_id>', DeleteView.as_view(), name='delete'),
]

terrapro_admin/urls.py
from django.conf import settings
from django.urls import path, include

from .views import HomeView


urlpatterns = [
    path('api/v1/', include([
        path('', include('api.urls', namespace='api')),
    ])),

    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('account.urls')),
    path('post/', include('post.urls')),
    path('city/', include('city.urls')),
    path('branch/', include('branch.urls')),
    path('report/', include('report.urls')),
]

branch/views.py
from django.shortcuts import render, redirect, reverse
from django.views import View

from api.models import Branche

from branch.form import BranchForm


class ListView(View):
    def get(self, request):
        branches = Branche.objects.order_by('id')

        return render(request, 'branches.html', context={'branches': branches})


class CreateView(View):
    def get(self, request):
        form = BranchForm()

        return render(request, 'branch.html', context={'form': form})

    def post(self, request):
        form = BranchForm(request.POST)

        if not form.is_valid():
            return render(request, 'branch.html', context={'form': form})

        form.save()

        return redirect(reverse('branch:list'))


class EditView(View):
    def get(self, request, branch_id):
        branch = self._get_branch(branch_id)

        form = BranchForm(instance=branch)

        return render(request, 'branch.html', context={'form': form})

    def post(self, request, branch_id):
        branch = self._get_branch(branch_id)

        form = BranchForm(request.POST, instance=branch)

        if not form.is_valid():
            return render(request, 'branch.html', context={'form': form})

        form.save()

        return redirect(reverse('branch:list'))

    def _get_branch(self, branch_id):
        return Branche.objects.get(pk=branch_id)


class DeleteView(View):
    def post(self, request, branch_id):
        Branche.objects.get(pk=branch_id).delete()

        return redirect(reverse('branch:list'))

branch/templates/branch.html
{% extends "base.html" %}
{% load html_attrs %}

{% block content %}
<form role="form" method="post" enctype="multipart/form-data" novalidate>
{% csrf_token %}
    <div class="post_form__contaner">
        <div class="card">
            <div class="card-header">
                Добавление филиала
            </div>
            <div class="card-body">
                <div class="form-group">
                    {{ form.address_rus.label_tag }}
                    {% if form.address_rus.errors %}
                        {{ form.address_rus|html_attrs:'"class": "form-control is-invalid"' }}
                    {% else %}
                        {{ form.address_rus|html_attrs:'"class": "form-control"' }}
                    {% endif %}
                    <h5 class="text-red">{{ form.address_rus.errors }}</h5>
                </div>
                <div class="form-group">
                    {{ form.address_uzb.label_tag }}
                    {% if form.address_uzb.errors %}
                        {{ form.address_uzb|html_attrs:'"class": "form-control is-invalid"' }}
                    {% else %}
                        {{ form.address_uzb|html_attrs:'"class": "form-control"' }}
                    {% endif %}
                    <h5 class="text-red">{{ form.address_uzb.errors }}</h5>
                </div>
                <div class="form-group">
                    {{ form.address_eng.label_tag }}
                    {% if form.address_eng.errors %}
                        {{ form.address_eng|html_attrs:'"class": "form-control is-invalid"' }}
                    {% else %}
                        {{ form.address_eng|html_attrs:'"class": "form-control"' }}
                    {% endif %}
                    <h5 class="text-red">{{ form.address_eng.errors }}</h5>
                </div>
                <div class="form-group">
                    {{ form.cites.label_tag }}
                    {% if form.cites.errors %}
                        {{ form.cites|html_attrs:'"class": "form-control is-invalid"' }}
                    {% else %}
                        {{ form.cites|html_attrs:'"class": "form-control"' }}
                    {% endif %}
                    <h5 class="text-red">{{ form.address_eng.errors }}</h5>
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-info">Сохранить</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

branch/templates/branches.html
{% extends "base.html" %}

{% block content %}
    <div class="post_list__container">
        <div class="card">
            <div class="card-header">
                <div class="card-header-buttons-container">
                    <a href="{% url 'branch:create' %}" class="btn btn-block btn-outline-success btn-create">
                        Добавить филиал <i class="fa fa-plus"></i>
                    </a>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th style="width: 20px">ID</th>
                            <th>Город</th>
                            <th>Адрес</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for branch in branches %}
                            <tr>
                                <td>{{ branch.id }}</td>
                                <td>{{ branch.city }}</td>
                                <td>{{ branch.address_rus }}</td>
                                <td class="edit-td">
                                    <div class="td-content">
                                        <a href="{% url 'branch:edit' branch_id=branch.id %}" class="btn btn-block btn-outline-primary edit-btn">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                    </div>
                                </td>
                                <td class="edit-td">
                                    <div class="td-content">
                                        <a href="{% url 'branch:delete' branch_id=branch.id %}" class="btn btn-block btn-outline-danger delete-btn">
                                            <i class="fa fa-trash-alt"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}